---

- name: Build the Hitchhiker Image
  hosts:
    - all
  vars:
    ansible_bender:
      base_image: python:3.8.10-alpine3.13
      cache_tasks: yes
      layering: yes

      working_container:
        volumes: [ ]

      target_image:
        name: test-hiker
        labels: { }
        environment: { }
        #        cmd: todo
        entrypoint:
          - /init
        ports: [ ]
        volumes: [ ]
        working_dir: "{{ hitchhiker_working_directory }}"

  tasks:
    - import_role:
        name: home-assistant-hitchhiker


