---

- name: Build the Hitchhiker Image
  hosts:
    - all
  vars:
    ansible_bender:
      base_image: python:3.8-buster
      cache_tasks: no
      layering: yes
      ansible_extra_args: -vvv

      working_container:
        volumes: [ ]

      target_image:
        name: test-hiker
        labels: { }
        environment: { }
        cmd: python3 -m /usr/src/homeassistant -c /config
        entrypoint: /bin/bash
        ports: [ ]
        volumes: [ ]
        working_dir: /usr/src

  tasks:
    - import_role:
        name: home-assistant-hitchhiker


