---

- name: Build the Hitchhiker Image
  hosts:
    - all
  vars:
    ansible_bender:
      base_image: python:3.8.11-slim-buster
      cache_tasks: yes
      layering: yes

      working_container:
        volumes: [ ]

      target_image:
        name: test-hiker
        labels: { }
        environment: { }
        #        cmd: todo
        entrypoint: python3 -m homeassistant -C /config
        ports: [ ]
        volumes: [ ]
        working_dir: /usr/src

  tasks:
    - import_role:
        name: home-assistant-hitchhiker


